### ISSUE TITLE
Failed to fetch on mobile device

### ISSUE THREAD

**Issue by shmbajaj** [rive-app/rive-react#134]
### TypeError: Failing to fetch.
- Failing to fetch rive animation on mobile device during initialization/initial-load, 
  but after changing routes/event animation gets loaded.

### Stacktrace
```javascript
TypeError: Failed to fetch
  at ? (../../instrument.ts:153:28)
  at ? (../rive/npm/canvas_advanced/canvas_advanced.mjs:102:147)
  at Module.<anonymous>(../rive/npm/canvas_advanced/canvas_advanced.mjs:101:1)
  at loadRuntime(../rive/src/rive.ts:190:5)
  at getInstance(../rive/src/rive.ts:207:21)
  at ? (../rive/src/rive.ts:219:21)
  at new Promise(<anonymous>)
  at awaitInstance(../rive/src/rive.ts:218:12)
  at init(../rive/src/rive.ts:1145:19)
  at new t(../rive/src/rive.ts:1097:10)
  at vb(../node_modules/@rive-app/react-canvas/dist/index.js:1:3212)
  at b(../node_modules/react-dom/cjs/react-dom.production.min.js:255:383)
  at If(../node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
  at cg(../node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
  at Jj(../node_modules/react-dom/cjs/react-dom.production.min.js:248:370)
  at yj(../node_modules/react-dom/cjs/react-dom.production.min.js:239:376)
  at b(../node_modules/react-dom/cjs/react-dom.production.min.js:123:115)
  at If(../node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
  at cg(../node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
  at fg(../node_modules/react-dom/cjs/react-dom.production.min.js:123:61)
  at gg(../node_modules/react-dom/cjs/react-dom.production.min.js:122:496)
  at Mj(../node_modules/react-dom/cjs/react-dom.production.min.js:240:66)
  at notify(../node_modules/react-redux/es/utils/Subscription.js:19:7)
  at onStateChange(../node_modules/react-redux/es/utils/Subscription.js:90:20)
  at i(../node_modules/react-redux/es/utils/Subscription.js:95:12)
  at dispatch(../node_modules/redux/es/redux.js:296:32)
  at call(middleware/index.ts:158:9)
  at tryCatch(../node_modules/regenerator-runtime/runtime.js:63:40)
  at _invoke(../node_modules/regenerator-runtime/runtime.js:294:22)
  at key(../node_modules/regenerator-runtime/runtime.js:119:21)
  at asyncGeneratorStep(../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:20)
  at _next(../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:9)
```

### Browser Info
- Chrome Mobile WebView
- 106.0.5249 version

### OS Info
- Andriod 12
- Samsung

### User Agent
- Mozilla/5.0 (Linux; Android 12; SM-M326B Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

**Comment by zplata** [comment]
Do you have a small repro sandbox to test against? it would be good to see how its been initiialized. And does this work ok on other devices/browsers?

**Comment by shmbajaj** [comment]
`Update:` There was issue with my code and have been fixed.
cc: @zplata
