### ISSUE TITLE
1.0.0 issues using the webgl renderer on Android

### ISSUE THREAD

**Issue by zplata** [rive-app/rive-react#63]
Caught on Discord that a React app on Android mobile was slow, and sometimes led to these errors - 
```
Uncaught RuntimeError: memory access out of bounds
    at rive.wasm:0x140a9c
    at rive.wasm:0x2e21d4
    at rive.wasm:0x76f9f
    at SMINumber.y.set [as value] (webgl_advanced.mjs:84:1)
    at StateMachineInput.set (rive.ts:312:1)
    at timer (App.js:151:1)
```

**Comment by caudetgit** [comment]
closing as stale
